### ISSUE TITLE
[Request] Replay Buffer

### ISSUE THREAD

**Issue by null-zero** [MisutaaAsriel/obs-toolbar#3]
# Request
Lovely plugin, my main use for OBS is as a more advanced shadowplay and as such having this display replay buffer status and a button to toggle it would be great

**Comment by MisutaaAsriel** [comment]
When I get to updating this, I'll look to see if that is exposed via the OBS plugin API. But I can only do what the API allows so no promises.

**Comment by Rinma** [comment]
Hi, I like this plugin but was also missing the replay buffer.
Because I had some spare time, I thought I give it a go. I would be happy about a review of my PR :)

**Comment by MisutaaAsriel** [comment]
> Hi, I like this plugin but was also missing the replay buffer. Because I had some spare time, I thought I give it a go. I would be happy about a review of my PR :)

I mentioned it in the PR but I need you to rebase and resubmit for testing. I had to do some changes to the repository to fix GitHub Actions when building the plugin, which resulted in the commit history changing and breaking the PR.

**Comment by MisutaaAsriel** [comment]
@Rinma It'll be a bit before I can get a new release published, since I haven't got generation of the WIX msi installer working just yet as part of GitHub actions.

But in the meantime, if you know where the plugin is installed, you can download and install the latest version using the build artifact here: https://github.com/MisutaaAsriel/obs-toolbar/actions/runs/8674784191
